import Footer from "@/components/shared/Footer";
import Navbar from "@/components/shared/Navbar";
import Sidebar from "@/components/shared/Sidebar";
import Title from "@/components/ui/Title";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Ad-doha Dashboard",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Navbar />
      <div className="py-4">
        <Title title="About Us" />
      </div>
      <div className="min-h-[500px] max-w-7xl mx-auto px-4 my-2  rounded-box bg-green-50 border mb-10">
        <div className="flex justify-between">
          <div className="w-[20%]">
            <Sidebar />
          </div>

          <div className="w-[80%]  bg-white my-3 rounded-lg p-2">
            {children}
          </div>
        </div>
      </div>
      <Footer />
    </>
  );
}
