export enum tagTypes {
  admin = "admin",
  faculty = "faculty",
  student = "student",
  course = "course",
  offeredCourse = "offeredCourse",
  enrolledCourse = "enrolledCourse",
  user = "user",
  book = "book",
  video = "video",
  department = "department",
  opinion = "opinion",
  teacher = "teacher",
  committee = "committee",
  author = "author",
  bookcategory = "bookcategory",
  transaction = "trans action",
  banner = "banner",
  subscribe = "subscribe",
  contact = "contact",
}

export const tagTypesList = [
  tagTypes.admin,
  tagTypes.faculty,
  tagTypes.student,
  tagTypes.course,
  tagTypes.offeredCourse,
  tagTypes.enrolledCourse,
  tagTypes.user,
  tagTypes.book,
  tagTypes.video,
  tagTypes.department,
  tagTypes.opinion,
  tagTypes.teacher,
  tagTypes.committee,
  tagTypes.author,
  tagTypes.bookcategory,
  tagTypes.transaction,
  tagTypes.banner,
  tagTypes.subscribe,
  tagTypes.contact,
];
