const assets = {
  banner: {
    slide1: require("../assets/banner/Slide -1.jpg"),
    slide2: require("../assets/banner/Slide -2.jpg"),
    slide3: require("../assets/banner/Slide -3.jpg"),
    slide4: require("../assets/banner/Slide -4.jpg"),
  },
  logo: {
    headerlogo: require("../assets/logo/logo.png"),
    footerlogo: require("../assets/logo/footer_logo.png"),
    logo: require("../assets/logo/favicon.webp"),
  },
  projects: {
    dawah: require("../assets/projects/দাওয়াহ.jpg"),
    education: require("../assets/projects/শিক্ষা.jpg"),
    services: require("../assets/projects/সেবা.jpg"),
  },
  services: {
    home: require("../assets/services/বাসস্থান র্নিমাণে সহায়তা.jpg"),
    educanalHelp: require("../assets/services/শিক্ষা সহায়তা.jpg"),
    employment: require("../assets/services/কর্মসংস্থান সহায়তা.jpg"),
    treatment: require("../assets/services/চিকিৎসা সহায়তা.jpg"),
    korjeHasana: require("../assets/services/কর্জে হাসানাহ.jpg"),
    low: require("../assets/services/আইনি সহায়তা.jpg"),
    sunnateKhotna: require("../assets/services/সুন্নতে খাৎনা.jpg"),
    marriage: require("../assets/services/বিয়ে.jpg"),
  },
  courses: {
    english: require("../assets/courses/English Course.jpg"),
    islamiNasid: require("../assets/courses/ইসলামী নাশিদ কোর্স web.jpg"),
    comIslamkhristan: require("../assets/courses/তুলনামূলক ধর্মতত্ত্ব- ইসলাম ও খ্রিস্টান.jpg"),
    comIslamBoudho: require("../assets/courses/তুলনামূলক ধর্মতত্ত্ব- ইসলাম ও বৌদ্ধধর্ম.jpg"),
    comIslamHindu: require("../assets/courses/তুলনামূলক ধর্মতত্ত্ব- ইসলাম ও হিন্দুধর্ম.jpg"),
    moulikIslam: require("../assets/courses/মৌলিক ইসলাম শিক্ষা.jpg"),
    sohihQuran: require("../assets/courses/সহিহ কুরআন শিক্ষা.jpg"),
  },

  faculties: {
    abdullalnoman: require("../assets/faculty/আব্দুল্লাহ আল নোমান.png"),
    abdullahSoad: require("../assets/faculty/আব্দুল্লাহ সোয়াদ.png"),
    arifulIslam: require("../assets/faculty/আরিফুল ইসলাম অপু.png"),
    jiaulHaque: require("../assets/faculty/জিয়াউল হক আনসারি.png"),
    tanvirAhmed: require("../assets/faculty/তানভির আহমেদ শরীফ.png"),
    deloarHossen: require("../assets/faculty/দেলোয়ার হোসেন.png"),
    noman: require("../assets/faculty/নোমান.png"),
    firdausHasan: require("../assets/faculty/ফিরদাউস হাসান.png"),
    khalidsaifullah: require("../assets/faculty/মাওলানা খালিদ মুহাম্মাদ সাইফুল্লাহ.png"),
    sorifulIslam: require("../assets/faculty/মাওলানা শরিফুল ইসলাম.png"),
    abuBakarSiddik: require("../assets/faculty/মুফতি আবু বকর সিদ্দীক.png"),
    musahidAli: require("../assets/faculty/মুশাহিদ আলী.png"),
    abdulKorim: require("../assets/faculty/শায়েখ আব্দুল করিম নায়েফ.png"),
    aminulIslamAzhari: require("../assets/faculty/শায়েখ ড. আমিনুল ইসলাম আজহারী.png"),
    forifulIslam: require("../assets/faculty/শায়েখ ফরিদুল ইসলাম.png"),
    salmanFarshi: require("../assets/faculty/সম্রাট সালমান ফারসি.png"),
    omorFaruk: require("../assets/faculty/ওমর_ফারুক.png"),
  },
  advisoryCommittees: {
    abdulKader: require("../assets/advisoryCommittee/আব্দুল কাদের সরকার.jpg"),
    muhammadSalman: require("../assets/advisoryCommittee/মাওলানা মুহাম্মদ সালমান.jpg"),
    ruhulAmin: require("../assets/advisoryCommittee/রুহুল আমিন সাদী.jpg"),
    abuHurayra: require("../assets/advisoryCommittee/শাইখ আবু হুরায়রা আজহারী.jpg"),
    umayerKobbadi: require("../assets/advisoryCommittee/শায়েখ উমায়ের কোব্বাদী.jpg"),
    gMMeherullah: require("../assets/advisoryCommittee/শায়েখ জি এম মেহেরুল্লাহ.jpg"),
    mujiburRahman: require("../assets/advisoryCommittee/শায়েখ মুফতি মুজিবুর রহমান.jpg"),
    saifulIslam: require("../assets/advisoryCommittee/হাফেজ মুফতি সাইফুল ইসলাম.jpg"),
    nadvi: require("../assets/advisoryCommittee/Nadbi.jpg"),
  },
  departments: {
    quranShikkha: require("../assets/department/quran.png"),
    islamShikkha: require("../assets/department/hadis.png"),
    dhormototto: require("../assets/department/open-book.png"),
    englishLanguage: require("../assets/department/English.png"),
    islamiNashid: require("../assets/department/নাশিদ.png"),
  },
  icons: {
    location: require("../assets/logo/location.png"),
    email: require("../assets/logo/email.png"),
    call: require("../assets/logo/call.webp"),
  },
  resourse: {
    book: require("../assets/resourses/book.gif"),
    video: require("../assets/resourses/video.gif"),
    gallery: require("../assets/resourses/gallery.gif"),
  },
  about: {
    aim: require("../assets/about/aim.png"),
    objective: require("../assets/about/uddesso.png"),
  },
};

export default assets;
